version: '3.2'
services:
  portal:
    image: 'nginx:latest'
    ports:
      - 80:80
    volumes:
      - ./dist:/usr/share/nginx/html
    container_name: nginx
    restart: always
    environment:
      - NGINX_HOST=portal.e-sapp.gov.zm
